image: gcc

# job:
#   tags:
#     - build
#     - run
    
stages:
    - build
    - run

build:
  stage: build
  
  script:
    - gcc helloworld.c -o hello
  artifacts:
    paths:
      - hello.exe
     

run:
  stage: run
  script:
    - ./hello
