image: node:8.9.0

# environment:
#     - MYSQL_SERVER_FOR_PHP : mysql:3306
#     - MYSQL_CONTAINER_NAME : engima_mysql
#     - MYSQL_DATABASE : engima_database
#     - MYSQL_USER : engima
#     - MYSQL_PASS : engimapw

# job:
#   tags:
#     - build
#     - run
variables:
    MYSQL_SERVER_FOR_PHP: 'mysql:3306'
    MYSQL_CONTAINER_NAME: 'engima_mysql'
    MYSQL_DATABASE: 'engima_database'
    MYSQL_USER: 'engima'
    MYSQL_PASS: 'engimapw'

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'


stages:
    - deploy

# build:
#   stage: build
  
#   script:
#     - gcc helloworld.c -o hello
  
  

#   artifacts:
#     paths:
#       - hello.exe
     

# run:
#   stage: run
#   script:
#     - ./hello

deploy:dev:
  stage: deploy
  script:
    - bash deploy/deploy.sh
  only:
    - master

