version: "3.6"
services:
  mysql:
    container_name: engima_mysql
    image: mysql:8.0.17
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PASSWORD=${MYSQL_PASS}
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - ./config/mysql/my.cnf:/etc/mysql/my.cnf
  php:
    container_name: engima_php
    build: ./docker/php
    ports:
      - "80:80"
    env_file:
      - ./.env
    volumes:
      - ./app:/var/www/html
      - ./config/apache/engima.conf:/etc/apache2/apache2.conf
      - ./config/php/engima.ini:/usr/local/etc/php/conf.d/engima.ini
